### ISSUE TITLE
What is the permission?

### ISSUE THREAD

**Issue by aarvndhNG** [Leader-txt/TShockPlugin-Shop#10]

**Comment by aarvndhNG** [comment]
> _No description provided._

How do I get coins to buy item 
@ACaiCat

**Comment by ACaiCat** [comment]
shop.admin --- Manage the shop system
use "/shop pay " to exchange coins in the player's inventory for money
Strike NPCs(such as green slime) to get money

**Comment by aarvndhNG** [comment]
![Screenshot_20230102-120354](https://user-images.githubusercontent.com/107058543/210200754-b5164a0e-ea7d-4982-8295-de40168d9921.png)
`

**Comment by aarvndhNG** [comment]
I have a issue

**Comment by ACaiCat** [comment]
Is "/shop pay"?

**Comment by aarvndhNG** [comment]
> Is "/shop pay"?

Yes i typed /shop pay

**Comment by ACaiCat** [comment]
I'm taking a class now, and I'll test and fix it in a moment

> > Is "/shop pay"?
> 
> Yes i typed /shop pay

**Comment by ACaiCat** [comment]
Try "/shop pay [money]"

**Comment by aarvndhNG** [comment]
> Try "/shop pay [money]"

Ok work
But the other players isn't get any coins to shop

**Comment by ACaiCat** [comment]
Striking monsters also can get money

**Comment by Leader-txt** [comment]
Can you leave us a contact method so that we can contact each other more convenient?
(Besides,the another is that I have a strong will to have a foreign friend.)

**Comment by aarvndhNG** [comment]
> Can you leave us a contact method so that we can contact each other more convenient? (Besides,the another is that I have a strong will to have a foreign friend.)

Oh sorry I'll leave now :(

**Comment by Leader-txt** [comment]
Shame!



---Original---
From: "That ***@***.***&gt;
Date: Mon, Jan 2, 2023 17:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Leader-txt/TShockPlugin-Shop] What is the permission? (Issue#10)




  
Can you leave us a contact method so that we can contact each other more convenient? (Besides,the another is that I have a strong will to have a foreign friend.)
  
Oh sorry I'll leave now :(
